In [20]:
import numpy as np

Vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
two dimensional: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 shape: (3, 5)

 dimension: 2

 data type: int64

 size: 15

 type: <class 'numpy.ndarray'>
[5 7 9]
[-3 -3 -3]
[1 4 9]
[1 2 3]
[5 2 3] [5 2 3] [5 2 3]
1
[1 2 3 4]
[7 6 5 4 3 2 1]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array2=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print("Vector:",array2)




In [21]:
a=array2.reshape(3,5)
print("two dimensional: \n",a)


two dimensional: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [22]:
print("shape:",a.shape) #(3, 5)
print("\n dimension:",a.ndim) 
print("\n data type:",a.dtype.name) 
print("\n size:",a.size) 
print("\n type:",type(a)) 


shape: (3, 5)

 dimension: 2

 data type: int64

 size: 15

 type: <class 'numpy.ndarray'>


In [23]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x-y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [24]:
a=np.array([1,2,3])
b=a.copy()
print(b)
b=a
c=a
b[0]=5
print(a,b,c)

[1 2 3]
[5 2 3] [5 2 3] [5 2 3]


In [25]:
a=np.array([1,2,3,4,5,6,7])
print(a[0])
print(a[0:4])


1
[1 2 3 4]


In [26]:
reverse_array = a[::-1]
print(reverse_array)



[7 6 5 4 3 2 1]


In [27]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)
print(b[1,1]) 
print(b[:,1]) 
print(b[1,:]) 
print(b[1,1:4]) 
print(b[-1,:])
print(b[:,-1]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]
